### ISSUE TITLE
Bug in grid_search

### ISSUE THREAD

**Issue by NavidHjzn** [RomainGoussault/Deepov#35]
I had this error while making a test : (happened only once)

runCutechess with command :
./cutechess-cli.sh -engine cmd=./Deepov dir=../ option.timeDivider=81  -engine cmd=./Deepov dir=../ -each proto=uci tc=100/0.5+0.01 -rounds 5 -pgnout a.out -openings file=openings.pgn -recover -repeat -site navid-N551JX -concurrency 7
Traceback (most recent call last):
  File "./tuner.py", line 99, in <module>
    main(sys.argv[1:]) # sys.argv[0] is the name of the script
  File "./tuner.py", line 57, in main
    best,elo=opt_gridSearch(parametersList)
  File "/home/navid/Chess/Deepov/DeepovTuning/optRoutines.py", line 44, in opt_gridSearch
    recursive_iterate(parametersList,0,n)
  File "/home/navid/Chess/Deepov/DeepovTuning/optRoutines.py", line 59, in recursive_iterate
    score = evaluate(command)
  File "/home/navid/Chess/Deepov/DeepovTuning/deepovFunction.py", line 19, in evaluate
    score = int(re.search(r'[-+]?\d+', s.decode('UTF-8')).group())
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by NavidHjzn** [comment]
set priority : critical

**Comment by RomainGoussault** [comment]
happened only once ?

**Comment by NavidHjzn** [comment]
it happens every tens of runs of cutechess-cli
